class TestData:
    chrome_executablePath = "F:/pack/chromedriver.exe"
    fireFox_executablePath = "F:/packages/geckodriver.exe"
    BASE_URL = "https://demo.actitime.com/login.do"
    LOGIN_PAGE_TITLE = "actiTIME - Login"
    HOME_PAGE_TITLE = "actiTIME - Login"
    USER_PAGE_TITLE = "actiTIME - User List"
    ALERT_TEXT = "Are you sure you want to delete this user account?"
    PROJECT_NAME = "ActiTime"
    TASK_NAME = "LOGIN MODULE"